apiVersion: apps/v1
kind: Deployment
metadata:
  name: lettuce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lettuce-app
  template:
    metadata:
      labels:
        app: lettuce-app
    spec:
      containers:
        - name: lettuce-app
          image: 0.0.0.0:0000/lettuce-app:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: lettuce-config
---
apiVersion: v1
kind: Service
metadata:
  name: lettuce-app
spec:
  type: NodePort
  selector:
    app: lettuce-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
